### ISSUE TITLE
User Feedback: Error or empty results when choosing any of the options "... and nearby .. on maps "

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#401]
User: I got a bug for the search „Herrenberg Markplatz“ – i clicked „Bushaltestellen in der Nähe“
![image](https://user-images.githubusercontent.com/83356918/117320417-80884200-ae8c-11eb-90f6-95cbcad13427.png)

When I tried reproducing the bug also with the other options, I got an empty screen
![image](https://user-images.githubusercontent.com/83356918/117320553-a31a5b00-ae8c-11eb-8c70-adc006a71ace.png)

**Comment by leonardehrenfried** [comment]
I think this has been fixed on dev: https://dev.stadtnavi.eu/inderhaehe/BUS/POS/Herrenberg%20Marktplatz%2C%20Rathausstaffel%2C%2071083%20Herrenberg::48.5964033,8.8704836

**Comment by hbruch** [comment]
Could you fix the text "in der haehe" should read "in der naehe", no?

**Comment by samia-roubaa** [comment]
> I think this has been fixed on dev: https://dev.stadtnavi.eu/inderhaehe/BUS/POS/Herrenberg%20Marktplatz%2C%20Rathausstaffel%2C%2071083%20Herrenberg::48.5964033,8.8704836
> 
> Can you confirm that, Samia?

No, unfortunately the problem still exists on the dev.
![image](https://user-images.githubusercontent.com/83356918/117465337-e2f74600-af51-11eb-93bc-95ebd229a1bc.png)

**Comment by MartinH-open** [comment]
> Could you fix the text "in der haehe" should read "in der naehe", no?

Sure - i noticed this artifact too. 
But anyhow - why translating URL pathnames like "nearby" to some language specific term ?
Better stay with the standard unique pathname and use the locale parameter to specify the language
