### ISSUE TITLE
Sharing options are not displayed

### ISSUE THREAD

**Issue by stadtnavimanager** [stadtnavi/digitransit-ui#951]
@hbruch all sharing option except taxi seem not to be displayed at the moment. Could you pls check?

<img width="564" alt="Image" src="https://github.com/user-attachments/assets/7af62edc-50b6-48f9-8edb-e627cf651b0f" />

**Comment by hbruch** [comment]
Fixed by enabling additional sharing services and #964

**Comment by stadtnavimanager** [comment]
@hbruch I still do not see any sharing options on the map, except of the taxi:

<img width="704" alt="Image" src="https://github.com/user-attachments/assets/7e667c76-6395-4f59-aefe-e9d527d5947f" />

**Comment by stadtnavimanager** [comment]
Unfortunaley, the carpool stops are still not on the map in the webversion.
Additionaly, when rental bikes are activated, also some E-Scooters are shown: 

<img width="932" alt="Image" src="https://github.com/user-attachments/assets/1e545adb-58cb-4072-b066-6f907bea03bf" />

At the same time in the app, only carpool stops, taxis and rental cars are shown. The rental cars use a different symbol than the web app:

![Image](https://github.com/user-attachments/assets/b420be63-6eaa-4da9-a29a-09f4f21fbcbe)

![Image](https://github.com/user-attachments/assets/5f22648d-3421-41a5-aa07-46a8cd6db9d8)


@hbruch could you please fix the described problems in the web app and clarify if the different display in the mobile app is a backend issue or something else and open an according issue? thank you

**Comment by Denis306** [comment]
This can be tested on V 1.14.20 (120) in Android and iOS.

**Comment by stadtnavimanager** [comment]
@Denis306 

- [ ] there is still a problem with the cargobike detail view - could you check that please? The rest in the app seems to be working at the moment

@hbruch 

- [ ] in the webversion the carpoolstops are not displayed
- [ ] for VOI E-Scooters there is no deeplink (might be a problem of the MobiData dataset?)

**Comment by hbruch** [comment]
@stadtnavimanager for me, carpool stops are display , e.g. here: https://dev.stadtnavi.eu/haltestellen/mfdz%3Aosm%3Aw30628218

<img width="549" alt="Image" src="https://github.com/user-attachments/assets/50364121-d033-4677-afb5-9da6bc6746a6" />

VOI, indeed, has no web urls for their [stations](https://api.mobidata-bw.de/sharing/gbfs/v3/voi_de/station_information)/[vehicles](https://api.mobidata-bw.de/sharing/gbfs/v3/voi_de/vehicle_status). I'll add https://www.voi.com/de and https://www.voi.com/en as fallback urls.

**Comment by stadtnavimanager** [comment]
@hbruch you are right about the carpoolstops. However, the stops in the app are different. For example when you go to "Degerloch" the app shows a lot of stops, the webversion none.

@hbruch @Denis306 do you know why that is the case? Is there a need to adapt something somehwere?

**Comment by hbruch** [comment]
A carpool as delivered by Amarillo could stop at every bus stop. As it would be confusing to display every stop where a carpool may stop by as a carpool stop, digitransit only displays [a subset](https://github.com/stadtnavi/digitransit-ui/blob/e841b9b081da0c1497305fde74b7f54fc4afa886/app/component/map/tile-layer/Stops.js#L93-L100) of them.

**Comment by stadtnavimanager** [comment]
@hbruch thanks for the explanation!

@Denis306 @SamuelRioTz @GustavoTCh

- [x]  could you please adapt the carpool stops in the app accordingly?
- [x] there is still a problem with the cargobike detail view - could you check that please? The rest in the app seems to be working at the moment
Screenshot:

![Image](https://github.com/user-attachments/assets/26bbb2fd-a9f1-4985-90d4-cd17cb002632)

**Comment by Denis306** [comment]
@stadtnavimanager can be tested on V 1.14.26 on Android and iOS.

**Comment by stadtnavimanager** [comment]
@Denis306 The null-mistake is fine now.

The icon is still a black dot. 
Is that something @hbruch has to fix, as it is an otp-layer or is there a problem with the .svg code in our POI-Layers sheet, @Denis306 ? Could you pls check where you get the icon from?

<img width="202" alt="Image" src="https://github.com/user-attachments/assets/16b5a65a-d744-4ba8-a252-cf4594966014" />

**Comment by stadtnavimanager** [comment]
I changed the .svg Code in the POI-Layer from this:

> <?xml version="1.0"?>
> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"    viewBox="0 0 34 34"
>    height="100%"
>    width="100%" version="1.1">
>   
>   <circle
>      cx="17"
>      cy="17"
>      r="17"
>      id="background_circle"
>     style="fill: var(--operatorbg, #ff834a)" fill="#ff834a"/>
> <g transform="translate(16,16) scale(1) translate(-17,-17)">
>     <path style="fill: var(--operatorfg, #ffffff)" d="M13.722,21.528l1.605,1.673v4.507h-1.434v-3.619l-2.356-2.048c-0.272-0.183-0.409-0.524-0.409-1.025           c0-0.409,0.137-0.751,0.409-1.024l2.049-2.049c0.182-0.272,0.523-0.409,1.024-0.409c0.432,0,0.819,0.137,1.161,0.409l1.399,1.4           c0.728,0.728,1.593,1.092,2.595,1.092v1.468c-1.435,0-2.664-0.512-3.687-1.536l-0.58-0.581L13.722,21.528z" fill="#ffffff"/>
>     <path style="fill: var(--operatorfg, #ffffff)" d="M17.171,17.875c-0.387,0-0.728-0.142-1.025-0.426c-0.295-0.285-0.443-0.62-0.443-1.007           c0-0.387,0.148-0.728,0.443-1.025c0.296-0.295,0.638-0.443,1.025-0.443c0.387,0,0.723,0.148,1.007,0.443           c0.284,0.296,0.426,0.638,0.426,1.025c0,0.387-0.142,0.723-0.426,1.007C17.894,17.732,17.558,17.875,17.171,17.875" fill="#ffffff"/>
>     <path style="fill: var(--operatorfg, #ffffff)" d="M27.536,26.019c-0.44-0.44-0.979-0.66-1.618-0.66c-0.638,0-1.174,0.22-1.606,0.66           c-0.433,0.44-0.649,0.979-0.649,1.618s0.216,1.174,0.649,1.607c0.433,0.433,0.968,0.649,1.606,0.649           c0.639,0,1.178-0.216,1.618-0.649c0.44-0.433,0.66-0.968,0.66-1.607S27.976,26.459,27.536,26.019z M26.948,28.654           c-0.285,0.278-0.627,0.417-1.028,0.417c-0.401,0-0.741-0.139-1.019-0.417c-0.278-0.278-0.417-0.618-0.417-1.019           s0.139-0.744,0.417-1.028c0.278-0.285,0.618-0.427,1.019-0.427c0.401,0,0.744,0.142,1.028,0.427           c0.285,0.285,0.427,0.628,0.427,1.028S27.232,28.376,26.948,28.654z" fill="#ffffff"/>
>     <path style="fill: var(--operatorfg, #ffffff)" d="M12.101,23.678c-0.695-0.705-1.554-1.058-2.578-1.058c-1.025,0-1.89,0.353-2.595,1.058           c-0.705,0.706-1.058,1.57-1.058,2.595c0,1.025,0.353,1.884,1.058,2.578c0.705,0.694,1.57,1.041,2.595,1.041           c1.024,0,1.883-0.347,2.578-1.041c0.694-0.694,1.041-1.553,1.041-2.578C13.142,25.249,12.795,24.385,12.101,23.678z M11.316,28.066           c-0.489,0.489-1.087,0.734-1.792,0.734c-0.705,0-1.308-0.245-1.809-0.734c-0.501-0.489-0.751-1.087-0.751-1.792           c0-0.705,0.25-1.309,0.751-1.809c0.501-0.501,1.104-0.751,1.809-0.751c0.705,0,1.303,0.25,1.792,0.751           c0.489,0.501,0.734,1.104,0.734,1.809C12.05,26.979,11.805,27.576,11.316,28.066z" fill="#ffffff"/>
>     <path style="fill: var(--operatorfg, #ffffff)" d="M22.937,27.646c0-0.83,0.288-1.54,0.864-2.129c0.576-0.589,1.279-0.884,2.109-0.884           c0.542,0,1.028,0.139,1.467,0.39l1.323-2.403H16.298l1.384,5.087h5.26C22.942,27.686,22.937,27.667,22.937,27.646z" fill="#ffffff"/>
>   <path style="fill: var(--operatorfg, #ffffff)" d="M17.762,2.758c2.786-0.022,5.062,2.219,5.083,5.005c0.022,2.786-2.219,5.062-5.005,5.083         c-1.364,0.011-2.673-0.531-3.631-1.502l0.794-0.816c0.719,0.752,1.718,1.171,2.758,1.159c1.045,0.013,2.049-0.402,2.78-1.148         c1.529-1.505,1.549-3.965,0.044-5.494c-0.014-0.015-0.029-0.029-0.044-0.044c-0.732-0.744-1.736-1.155-2.78-1.138         c-2.158-0.006-3.911,1.738-3.917,3.896c0,0.004,0,0.007,0,0.011h1.685l-2.265,2.254V9.949l-2.146-2.146h1.685         c-0.006-2.78,2.243-5.038,5.023-5.044c0.007,0,0.014,0,0.022,0L17.762,2.758z M17.204,5.57h0.848v2.361l1.964,1.181l-0.419,0.687         L17.204,8.35L17.204,5.57z" fill="#ffffff"/>
>     </g>
> </svg>

to this:

> <?xml version="1.0"?>
> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"    viewBox="0 0 34 34"
>    height="100%"
>    width="100%" version="1.1">
>   
>   <circle
>      cx="17"
>      cy="17"
>      r="17"
>      id="background_circle"
>     fill="#ff834a"/>
> <g transform="translate(16,16) scale(1) translate(-17,-17)">
>     <path d="M13.722,21.528l1.605,1.673v4.507h-1.434v-3.619l-2.356-2.048c-0.272-0.183-0.409-0.524-0.409-1.025           c0-0.409,0.137-0.751,0.409-1.024l2.049-2.049c0.182-0.272,0.523-0.409,1.024-0.409c0.432,0,0.819,0.137,1.161,0.409l1.399,1.4           c0.728,0.728,1.593,1.092,2.595,1.092v1.468c-1.435,0-2.664-0.512-3.687-1.536l-0.58-0.581L13.722,21.528z" fill="#ffffff"/>
>     <path d="M17.171,17.875c-0.387,0-0.728-0.142-1.025-0.426c-0.295-0.285-0.443-0.62-0.443-1.007           c0-0.387,0.148-0.728,0.443-1.025c0.296-0.295,0.638-0.443,1.025-0.443c0.387,0,0.723,0.148,1.007,0.443           c0.284,0.296,0.426,0.638,0.426,1.025c0,0.387-0.142,0.723-0.426,1.007C17.894,17.732,17.558,17.875,17.171,17.875" fill="#ffffff"/>
>     <path d="M27.536,26.019c-0.44-0.44-0.979-0.66-1.618-0.66c-0.638,0-1.174,0.22-1.606,0.66           c-0.433,0.44-0.649,0.979-0.649,1.618s0.216,1.174,0.649,1.607c0.433,0.433,0.968,0.649,1.606,0.649           c0.639,0,1.178-0.216,1.618-0.649c0.44-0.433,0.66-0.968,0.66-1.607S27.976,26.459,27.536,26.019z M26.948,28.654           c-0.285,0.278-0.627,0.417-1.028,0.417c-0.401,0-0.741-0.139-1.019-0.417c-0.278-0.278-0.417-0.618-0.417-1.019           s0.139-0.744,0.417-1.028c0.278-0.285,0.618-0.427,1.019-0.427c0.401,0,0.744,0.142,1.028,0.427           c0.285,0.285,0.427,0.628,0.427,1.028S27.232,28.376,26.948,28.654z" fill="#ffffff"/>
>     <path d="M12.101,23.678c-0.695-0.705-1.554-1.058-2.578-1.058c-1.025,0-1.89,0.353-2.595,1.058           c-0.705,0.706-1.058,1.57-1.058,2.595c0,1.025,0.353,1.884,1.058,2.578c0.705,0.694,1.57,1.041,2.595,1.041           c1.024,0,1.883-0.347,2.578-1.041c0.694-0.694,1.041-1.553,1.041-2.578C13.142,25.249,12.795,24.385,12.101,23.678z M11.316,28.066           c-0.489,0.489-1.087,0.734-1.792,0.734c-0.705,0-1.308-0.245-1.809-0.734c-0.501-0.489-0.751-1.087-0.751-1.792           c0-0.705,0.25-1.309,0.751-1.809c0.501-0.501,1.104-0.751,1.809-0.751c0.705,0,1.303,0.25,1.792,0.751           c0.489,0.501,0.734,1.104,0.734,1.809C12.05,26.979,11.805,27.576,11.316,28.066z" fill="#ffffff"/>
>     <path d="M22.937,27.646c0-0.83,0.288-1.54,0.864-2.129c0.576-0.589,1.279-0.884,2.109-0.884           c0.542,0,1.028,0.139,1.467,0.39l1.323-2.403H16.298l1.384,5.087h5.26C22.942,27.686,22.937,27.667,22.937,27.646z" fill="#ffffff"/>
>   <path d="M17.762,2.758c2.786-0.022,5.062,2.219,5.083,5.005c0.022,2.786-2.219,5.062-5.005,5.083         c-1.364,0.011-2.673-0.531-3.631-1.502l0.794-0.816c0.719,0.752,1.718,1.171,2.758,1.159c1.045,0.013,2.049-0.402,2.78-1.148         c1.529-1.505,1.549-3.965,0.044-5.494c-0.014-0.015-0.029-0.029-0.044-0.044c-0.732-0.744-1.736-1.155-2.78-1.138         c-2.158-0.006-3.911,1.738-3.917,3.896c0,0.004,0,0.007,0,0.011h1.685l-2.265,2.254V9.949l-2.146-2.146h1.685         c-0.006-2.78,2.243-5.038,5.023-5.044c0.007,0,0.014,0,0.022,0L17.762,2.758z M17.204,5.57h0.848v2.361l1.964,1.181l-0.419,0.687         L17.204,8.35L17.204,5.57z" fill="#ffffff"/>
>     </g>
> </svg>

let's see, if this helps

**Comment by stadtnavimanager** [comment]
ok, apperently I cannot paste the code :D but let's see anyway what happens. I took out style="fill: var(--operatorfg, #ffffff)" and just used fill="#ffffff"

**Comment by stadtnavimanager** [comment]
Ok, my change did not work. The icons disappeard completely in the app... I changed it back.
@hbruch @Denis306 please help :)
